### ISSUE TITLE
Spell casting time in combat

### ISSUE THREAD

**Issue by slowdive-fan** [IceBlinkEngine/IB2Engine#12]
Add spell casting time in combat system...also account for if caster it's hit anytime during the round before the spell is actually cast, caster can lose the spell on a failed concentration check. If hit before the caster's turn, and fails a check, then when it is the caster's turn, they can't cast a spell that round.

**Comment by youngneil1** [comment]
Great for tactics in combat (block enemies from casters with tanks). Also, a very fine tool to balance out those area effect spells, e.g. fireball. We might think about allowing attacks of opportunity also when moving around a blocking fighter in close quarter (see D&D 3rd edition, which only allowed one square of such close quarter move without triggering an AoO).
