### ISSUE TITLE
Rotate/flip tiles

### ISSUE THREAD

**Issue by slowdive-fan** [IceBlinkEngine/IB2Engine#16]
Allow to rotate and flip tiles if the PC dx engine will allow it. Add two new properties to Tile and TileEnc called rotate and flip. Rotate is an integer of 1,2,3,or 4. Flip is a bool.

**Comment by youngneil1** [comment]
Good stuff. Saves storage space, eg one road tile could be used for vertical and horizontal road (rotate 90 degree). Mayhaps have two different kind of flips, too? One through horizontal mirror axis, one through vertical mirror axis (or can teh later be doen with one flip and turn, hmmm)? Will rotate and flip be toolset functions while building a map in the editor?
Food for thought for later:
Shrink, enlarge, tint non-transparent image parts with color x,  and change transparency might be long term goals for more tile manipulation operations (e.g. create organic, varied forest from one tree tile), reducing the number of required tile png and the need to switch to a graphic programs for these scenarios. Shrink and enlarge will break standard dst square borders and will likely need checks for oversized tiles, like large creatures. Once going down that road, rotate could operate a full 360 degree, allowing odd angles or slight angle variations (e.g. 88degree standing tree). Tiles in same layer might have a new priorityNumber / zDepth property that decides whom to render first (underneath) in the same layer.

**Comment by slowdive-fan** [comment]
Also add shift x pixels and shift y pixels (can be positive or negative integer). Would be nice to be able to select an existing tile for editing and then be able to modify its rotation, flip, shift, scale, tint, etc.
